name: Scrape
on:
  #schedule:
  #  - cron: "0 9 * * *" # 10 a.m. every day UTC

  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pipenv"
      - run: pipenv install jupyter pandas beautifulsoup4 requests datetime dateparser

      - name: Run scraper
        run: pipenv run jupyter execute scrape.ipynb

      - name: Add and commit
        run: |-
          git add .
          git config user.name "Automatic Scrape Action"
          git config user.email "actions@users.noreply.github.com"	
          git commit -m "add newly scraped data"
      - name: Git push
        run: git push
